version: '3.8'

services:

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "parking_db"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./ParkingManagment
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: parking_db
      MYSQL_USER: root
      MYSQL_PASSWORD:

  frontend:
    build: ./frontend/clientside
    ports:
      - "3000:3000"
    depends_on:
      - backend
